DROP TABLE gsa_data.general;

CREATE TABLE gsa_data.general
(
    id serial not null primary key,
    report_id text,
    auditee_uei text,
    audit_year smallint,
    auditee_certify_name text,
    auditee_certify_title text,
    auditee_contact_name text,
    auditee_email text,
    auditee_name text,
    auditee_phone text,
    auditee_contact_title text,
    auditee_address_line_1 text,
    auditee_city text,
    auditee_state text,
    auditee_ein text,
    auditee_zip text,
    auditor_phone text,
    auditor_state text,
    auditor_city text,
    auditor_contact_title text,
    auditor_address_line_1 text,
    auditor_zip text,
    auditor_country text,
    auditor_contact_name text,
    auditor_email text,
    auditor_firm_name text,
    auditor_foreign_address text,
    auditor_ein text,
    cognizant_agency text,
    oversight_agency text,
    date_created date,
    ready_for_certification_date date,
    auditor_certified_date date,
    auditee_certified_date date,
    submitted_date date,
    fac_accepted_date date,
    fy_end_date date,
    fy_start_date date,
    audit_type text,
    gaap_results text,
    sp_framework_basis text,
    is_sp_framework_required text,
    sp_framework_opinions text,
    is_going_concern_included bool,
    is_internal_control_deficiency_disclosed bool,
    is_internal_control_material_weakness_disclosed bool,
    is_material_noncompliance_disclosed bool,
    dollar_threshold money,
    is_low_risk_auditee bool,
    agencies_with_prior_findings text,
    entity_type text,
    number_months text,
    audit_period_covered text,
    total_amount_expended text,
    type_audit_code text,
    is_public bool,
    data_source text
);

ALTER TABLE gsa_data.general OWNER TO facdata;


